services:

  redis:
    image: redis/redis-stack:7.2.0-v11
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass passWd"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

